# Generated by Django 2.2.4 on 2019-08-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='default', max_length=70, unique=True),
            preserve_default=False,
        ),
    ]
